-- Create customers table
CREATE TABLE customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    mobile VARCHAR(20),
    tax_id VARCHAR(50),
    category_id BIGINT,
    credit_limit DECIMAL(19,2) DEFAULT 0.00,
    current_balance DECIMAL(19,2) DEFAULT 0.00,
    available_credit DECIMAL(19,2) DEFAULT 0.00,
    total_sales DECIMAL(19,2) DEFAULT 0.00,
    total_payments DECIMAL(19,2) DEFAULT 0.00,
    loyalty_points INT DEFAULT 0,
    loyalty_tier VARCHAR(20),
    total_points_earned INT DEFAULT 0,
    total_points_redeemed INT DEFAULT 0,
    payment_terms VARCHAR(20) DEFAULT 'COD',
    discount_percentage DECIMAL(5,2) DEFAULT 0.00,
    registration_date DATE,
    last_purchase_date DATE,
    notes TEXT,
    is_vip BOOLEAN DEFAULT FALSE,
    is_credit_allowed BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    INDEX idx_customer_code (code),
    INDEX idx_customer_email (email),
    INDEX idx_customer_phone (phone),
    INDEX idx_customer_category (category_id),
    INDEX idx_customer_status (status),
    INDEX idx_customer_created (created_at),
    FOREIGN KEY (category_id) REFERENCES customer_categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

