-- Create discounts table
CREATE TABLE discounts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    discount_type VARCHAR(20) NOT NULL,
    discount_value DECIMAL(19,2) NOT NULL,
    max_discount_amount DECIMAL(19,2),
    min_purchase_amount DECIMAL(19,2),
    max_purchase_amount DECIMAL(19,2),
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    usage_limit INT,
    usage_count INT DEFAULT 0,
    per_customer_limit INT,
    is_cumulative BOOLEAN DEFAULT FALSE,
    applies_to_items BOOLEAN DEFAULT TRUE,
    applies_to_categories BOOLEAN DEFAULT FALSE,
    item_ids VARCHAR(1000),
    category_ids VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    is_deleted BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id),
    INDEX idx_discount_code (code),
    INDEX idx_discount_dates (start_date, end_date),
    INDEX idx_discount_status (status),
    INDEX idx_discount_type (discount_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

