-- Create promotions table
CREATE TABLE promotions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    promotion_type VARCHAR(30) NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    buy_quantity INT,
    get_quantity INT,
    get_discount_percentage DECIMAL(5,2),
    bundle_price DECIMAL(19,2),
    discount_amount DECIMAL(19,2),
    discount_percentage DECIMAL(5,2),
    min_purchase_amount DECIMAL(19,2),
    max_discount_amount DECIMAL(19,2),
    usage_limit INT,
    usage_count INT DEFAULT 0,
    per_customer_limit INT,
    priority INT DEFAULT 0,
    is_cumulative BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    is_deleted BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id),
    INDEX idx_promotion_code (code),
    INDEX idx_promotion_dates (start_date, end_date),
    INDEX idx_promotion_status (status),
    INDEX idx_promotion_type (promotion_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

